### ISSUE TITLE
tree-sitter: Parser dir should be read/write

### ISSUE THREAD

**Issue by soupglasses** [DieracDelta/vimconfig#5]
Since tree-sitter is fully inside of `/nix/store`, it will always be read only. Are there any ways to suppress or avoid this error?

Used: `nix run github:DieracDelta/vimconfig`.

I know one alternative is to link every tree-sitter parser to your `~/.config/nvim/parser` directory, but that misses the point of having it be a simple package that is `nix run ...`-able.

<details>
<summary>Log output</summary>

```console
Ignoring invalid config key 'cmp'                                                                                                                           
Error detected while processing /nix/store/khcglwzzqs53sq3f3iixxyqdiwg51pm3-init.vim:                                                                       
line   41:                                                                                                                                                  
Parser dir ' /nix/store/nij79rv7galadrkm84nykg8qkzsy44mc-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/parser ' should be read/write (see README on how to configure an alternative install location) /nix/store/nij79rv7galadrkm84nykg8qkzsy44mc-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/parser '
```
</details>

**Comment by soupglasses** [comment]
This seems to come from NixOS/nixpkgs#189838 and adding `ensure_installed = {}` to the config section of tree-sitter should apparently help this.

**Comment by DieracDelta** [comment]
I've been bothered by this problem for about a week and was unsure of the cause. Thank you for your time and the fix!
