### ISSUE TITLE
trouble editing C files

### ISSUE THREAD

**Issue by algoatson** [DieracDelta/vimconfig#6]
This is an amazing vimconfig, and i like using it, however recently i tried writing C with this config and i keep getting this error whenever i type something, it's unusable.
![image](https://github.com/DieracDelta/vimconfig/assets/142265437/4d015790-7337-44be-837a-4d3a00641ca6)

I am not sure how i  go about fixing this.

Steps to reproduce:
- nix run github:DieracDelta/vimconfig
- :edit do.c
- and try to type anything

I found this error message after building the project, i'm not sure if this helps
![image](https://github.com/DieracDelta/vimconfig/assets/142265437/66a73dad-9c96-4c8c-8c46-52834ba818ad)

Was able to temporarily fix by commenting out the following.
![image](https://github.com/DieracDelta/vimconfig/assets/142265437/c3ecf1dd-3d96-40b9-aa35-69827764c082)

**Comment by DieracDelta** [comment]
I've been seeing this recently and haven't figured out why this happens. Did you manage to fix this?

**Comment by algoatson** [comment]
I commented down this part in modules/lsp.nix
![image](https://github.com/DieracDelta/vimconfig/assets/142265437/f93bb61d-6e1b-486e-acbd-a536b478b3e9)

not a great fix, but works just fine.
